configured_endpoints: 89
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/knock%2Fknock-a1c3daf670a5df363f4b43b9e5bb9bfc8ca0e03dd4aabc938bf5bbbaadf9d25c.yml
openapi_spec_hash: f678482f5c48c1206342e8ec7d2b3abb
config_hash: 48dfe7e877aed766b63cb076dfe873ad
